var name = "Rafsan Hasan";
console.log(typeof name);
var promise = "I Am Rafsan Hasan"
console.log(promise.toLowerCase());
console.log(promise.indexOf('Rafsan'));
var dream ="I Want to be a engineer";
console.log(dream.split(' '));
var number1 = '30';
var number2 = 15.5;
number1 =parseFloat(number1)
console.log(number1 + number2);
var number1 = '30.5';
var number2 = 15;
number1 =parseInt(number1);
console.log(number1 + number2);
var number1 = '30.5';
var number2 = 15;
number1 =+number1;
console.log(number1 + number2);
var number1 = 0.1;
var number2 = 0.2;
console.log(number1 + number2);
var number1 = 0.1;
var number2 = 0.2;
var total =number1+number2;
total = total.toFixed(1);
console.log(total);
var number = -5;
var result = Math.abs(number);
console.log(result);
var number = 5.5445;
var result = Math.round(number);
console.log(result);
var number = 5.5445;
var result = Math.ceil(number);
console.log(result);
var number = 5.5445;
var result = Math.floor(number);
console.log(result);
var number = Math.random()*100;
var result = Math.round(number);
console.log(result);